In [ ]:
# ============================================================================
# COMBINE FINAL METRICS FROM ALL EXPERIMENT FOLDERS SUMMARIZATION WITHOUT RAG
# ============================================================================
import pandas as pd
from pathlib import Path
from google.colab import drive

drive.mount('/content/drive')

PROJECT_DIR = Path("/content/drive/MyDrive/Colab Notebooks/Masters/Masters_Thesis_Project")

EXPERIMENTS_DIR = PROJECT_DIR / "outputs" / "experiments"

OUTPUT_DIR = PROJECT_DIR / "outputs" / "final_comparison" / "summarization" / "non_rag"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

COMBINED_FILE = OUTPUT_DIR / "non_rag_summarization_final_metrics_all_experiments.csv"

all_rows = []

# Loop through each experiment folder
for exp_folder in EXPERIMENTS_DIR.iterdir():

    if exp_folder.is_dir():

        # Find final metrics file inside this folder
        final_metric_files = list(exp_folder.glob("*_final_metrics.csv"))

        if len(final_metric_files) == 0:
            print(f"No final metrics found in: {exp_folder.name}")
            continue

        # There should be only one
        file = final_metric_files[0]

        try:
            temp_df = pd.read_csv(file)

            if len(temp_df) == 0:
                print(f"Empty file: {file}")
                continue

            row = temp_df.iloc[0].to_dict()

            # Optional: add folder name for safety/debugging
            row["experiment_folder"] = exp_folder.name

            all_rows.append(row)

            print(f"Loaded: {exp_folder.name}")

        except Exception as e:
            print(f"Failed reading {file}: {e}")

# Combine all
combined_df = pd.DataFrame(all_rows)

# Save
combined_df.to_csv(COMBINED_FILE, index=False)

print("\n==============================")
print("FINAL COMBINED FILE SAVED AT:")
print(COMBINED_FILE)
print("==============================")

display(combined_df)

Mounted at /content/drive
Loaded: exp_s_01_zero_shot_without_rag_llama3_1_8b_instant
Loaded: exp_s_02_zero_shot_without_rag_llama-3.3-70b-versatile
Loaded: exp_s_03_zero_shot_without_rag_openai_gpt-oss-120b
Loaded: exp_s_04_few_shot_without_rag_llama3_1_8b_instant
Loaded: exp_s_05_few_shot_without_rag_llama-3.3-70b-versatile
Loaded: exp_s_06_few_shot_without_rag_openai_gpt-oss-120b
Loaded: exp_s_07_chain_of_thought_without_rag_llama3_1_8b_instant
Loaded: exp_s_08_chain_of_thought_without_rag_llama-3.3-70b-versatile
Loaded: exp_s_09_chain_of_thought_without_rag_openai_gpt-oss-120b
Loaded: exp_s_10_style_based_without_rag_llama3_1_8b_instant
Loaded: exp_s_11_style_based_without_rag_llama-3.3-70b-versatile
Loaded: exp_s_12_style_based_without_rag_openai_gpt-oss-120b
Loaded: exp_s_13_self_consistency_without_rag_llama3_1_8b_instant
Loaded: exp_s_14_self_consistency_without_rag_llama-3.3-70b-versatile
Loaded: exp_s_15_self_consistency_without_rag_openai_gpt_oss_120b

==============================
FINAL COMBINED FILE SAVED AT:
/content/drive/MyDrive/Colab Notebooks/Masters/Masters_Thesis_Project/outputs/final_comparison/summarization/non_rag/non_rag_summarization_final_metrics_all_experiments.csv
==============================

,experiment_id,prompt_type,model_name,temperature,max_tokens,num_samples_completed,rougeL_f1_mean,rougeL_f1_median,rougeL_f1_std,rougeL_f1_min,...,compression_ratio_max,top_k_skill_coverage_mean,top_k_skill_coverage_median,top_k_skill_coverage_std,top_k_skill_coverage_min,top_k_skill_coverage_max,global_skill_overlap,hallucination_prevalence,hallucination_density,experiment_folder
0,exp_s_01_zero_shot_without_rag_llama3_1_8b_ins...,zero_shot,llama-3.1-8b-instant,0.0,700,100,0.4514,0.4556,0.0851,0.2563,...,1.5500,0.402,0.4,0.2318,0.0,1.0,0.4041,1.0,9.55,exp_s_01_zero_shot_without_rag_llama3_1_8b_ins...
1,exp_s_02_zero_shot_without_rag_llama-3.3-70b-v...,zero_shot,llama-3.3-70b-versatile,0.0,700,100,0.4366,0.4421,0.0827,0.2028,...,7.2603,0.372,0.4,0.2274,0.0,0.8,0.3820,1.0,6.60,exp_s_02_zero_shot_without_rag_llama-3.3-70b-v...
2,exp_s_03_zero_shot_without_rag_openai_gpt-oss-...,zero_shot,openai/gpt-oss-120b,0.0,700,100,0.4357,0.4326,0.0681,0.2952,...,1.2740,0.366,0.4,0.2345,0.0,1.0,0.3751,1.0,6.01,exp_s_03_zero_shot_without_rag_openai_gpt-oss-...
3,exp_s_04_few_shot_without_rag_llama3_1_8b_instant,few_shot,llama-3.1-8b-instant,0.0,700,100,0.3563,0.3519,0.0736,0.2170,...,1.1883,0.324,0.4,0.2340,0.0,1.0,0.3954,1.0,6.80,exp_s_04_few_shot_without_rag_llama3_1_8b_instant
4,exp_s_05_few_shot_without_rag_llama-3.3-70b-ve...,few_shot,llama-3.3-70b-versatile,0.0,700,100,0.3635,0.3598,0.0644,0.1858,...,0.7671,0.310,0.4,0.2077,0.0,0.8,0.3299,1.0,4.97,exp_s_05_few_shot_without_rag_llama-3.3-70b-ve...
5,exp_s_06_few_shot_without_rag_openai_gpt-oss-120b,few_shot,openai/gpt-oss-120b,0.0,700,100,0.4099,0.3949,0.0755,0.2484,...,1.0000,0.364,0.4,0.2263,0.0,0.8,0.3664,1.0,5.10,exp_s_06_few_shot_without_rag_openai_gpt-oss-120b
6,exp_s_07_chain_of_thought_without_rag_llama3_1...,chain_of_thought,llama-3.1-8b-instant,0.0,700,100,0.4646,0.4620,0.0814,0.2807,...,1.4750,0.412,0.4,0.2324,0.0,1.0,0.4145,1.0,11.91,exp_s_07_chain_of_thought_without_rag_llama3_1...
7,exp_s_08_chain_of_thought_without_rag_llama-3....,chain_of_thought,llama-3.3-70b-versatile,0.0,700,100,0.4487,0.4468,0.0839,0.2193,...,3.4747,0.396,0.4,0.2378,0.0,1.0,0.4180,1.0,10.44,exp_s_08_chain_of_thought_without_rag_llama-3....
8,exp_s_09_chain_of_thought_without_rag_openai_g...,chain_of_thought,openai/gpt-oss-120b,0.0,700,100,0.4346,0.4331,0.0760,0.2596,...,1.2500,0.374,0.4,0.2214,0.0,1.0,0.3791,1.0,6.05,exp_s_09_chain_of_thought_without_rag_openai_g...
9,exp_s_10_style_based_without_rag_llama3_1_8b_i...,style_based,llama-3.1-8b-instant,0.0,700,100,0.4499,0.4496,0.0868,0.2421,...,1.1750,0.392,0.4,0.2360,0.0,1.0,0.4255,1.0,9.90,exp_s_10_style_based_without_rag_llama3_1_8b_i...
10,exp_s_11_style_based_without_rag_llama-3.3-70b...,style_based,llama-3.3-70b-versatile,0.0,700,100,0.4546,0.4457,0.0686,0.3285,...,1.2329,0.406,0.4,0.2335,0.0,1.0,0.3983,1.0,7.63,exp_s_11_style_based_without_rag_llama-3.3-70b...
11,exp_s_12_style_based_without_rag_openai_gpt-os...,style_based,openai/gpt-oss-120b,0.0,700,100,0.4572,0.4496,0.0901,0.2723,...,1.1918,0.406,0.4,0.2282,0.0,1.0,0.4116,1.0,6.01,exp_s_12_style_based_without_rag_openai_gpt-os...
12,exp_s_13_self_consistency_without_rag_llama3_1...,self_consistency,llama-3.1-8b-instant,0.3,700,100,0.4577,0.4511,0.0810,0.2705,...,1.4000,0.386,0.4,0.2366,0.0,1.0,0.4035,1.0,11.66,exp_s_13_self_consistency_without_rag_llama3_1...
13,exp_s_14_self_consistency_without_rag_llama-3....,self_consistency,llama-3.3-70b-versatile,0.3,700,100,0.4483,0.4404,0.0812,0.2254,...,7.9857,0.388,0.4,0.2392,0.0,0.8,0.4087,1.0,10.60,exp_s_14_self_consistency_without_rag_llama-3....
14,exp_s_15_self_consistency_without_rag_openai_g...,self_consistency,openai/gpt-oss-120b,0.3,700,100,0.4474,0.4277,0.0823,0.2752,...,1.2740,0.380,0.4,0.2387,0.0,1.0,0.3884,1.0,6.51,exp_s_15_self_consistency_without_rag_openai_g...

In [ ]:
# ============================================================================
# COMBINE FINAL METRICS FROM ALL EXPERIMENT FOLDERS OF SUMMARIZATION WITH RAG
# ============================================================================
import pandas as pd
from pathlib import Path
from google.colab import drive

drive.mount('/content/drive')

PROJECT_DIR = Path("/content/drive/MyDrive/Colab Notebooks/Masters/Masters_Thesis_Project")

EXPERIMENTS_DIR = PROJECT_DIR / "outputs" / "experiments" / "summarization_with_RAG"

OUTPUT_DIR = PROJECT_DIR / "outputs" / "final_comparison" / "summarization" / "rag"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

COMBINED_FILE = OUTPUT_DIR / "rag_summarization_final_metrics_all_experiments.csv"

all_rows = []

# Loop through each experiment folder
for exp_folder in EXPERIMENTS_DIR.iterdir():

    if exp_folder.is_dir():

        # Find final metrics file inside this folder
        final_metric_files = list(exp_folder.glob("*_final_metrics.csv"))

        if len(final_metric_files) == 0:
            print(f"No final metrics found in: {exp_folder.name}")
            continue

        # There should be only one
        file = final_metric_files[0]

        try:
            temp_df = pd.read_csv(file)

            if len(temp_df) == 0:
                print(f"Empty file: {file}")
                continue

            row = temp_df.iloc[0].to_dict()

            # Optional: add folder name for safety/debugging
            row["experiment_folder"] = exp_folder.name

            all_rows.append(row)

            print(f"Loaded: {exp_folder.name}")

        except Exception as e:
            print(f"Failed reading {file}: {e}")

# Combine all
combined_df = pd.DataFrame(all_rows)

# Save
combined_df.to_csv(COMBINED_FILE, index=False)

print("\n==============================")
print("FINAL COMBINED FILE SAVED AT:")
print(COMBINED_FILE)
print("==============================")

display(combined_df)

Mounted at /content/drive
Loaded: exp_s_R01_summarization_zero_shot_chromadb_llama-3.1-8b-instant
Loaded: exp_s_R02_summarization_zero_shot_chromadb_llama-3.3-70b-versatile
Loaded: exp_s_R03_summarization_zero_shot_chromadb_openai-gpt-oss-120b
Loaded: exp_s_R04_summarization_few_shot_chromadb_llama-3.1-8b-instant
Loaded: exp_s_R05_summarization_few_shot_chromadb_llama-3.3-70b-versatile
Loaded: exp_s_R06_summarization_few_shot_chromadb_openai-gpt-oss-120b
Loaded: exp_s_R07_summarization_chain_of_thought_chromadb_llama-3.1-8b-instant
Loaded: exp_s_R08_summarization_chain_of_thought_chromadb_llama-3.3-70b-versatile
Loaded: exp_s_R09_summarization_chain_of_thought_chromadb_openai-gpt-oss-120b
Loaded: exp_s_R10_summarization_style_based_chromadb_llama-3.1-8b-instant
Loaded: exp_s_R11_summarization_style_based_chromadb_llama-3.3-70b-versatile
Loaded: exp_s_R12_summarization_style_based_chromadb_openai-gpt-oss-120b
Loaded: exp_s_R13_summarization_self_consistency_chromadb_llama-3.1-8b-instant
Loaded: exp_s_R15_summarization_self_consistency_chromadb_openai_gpt-oss-120b
Loaded: exp_s_R14_summarization_self_consistency_chromadb_llama-3.3-70b-versatile

==============================
FINAL COMBINED FILE SAVED AT:
/content/drive/MyDrive/Colab Notebooks/Masters/Masters_Thesis_Project/outputs/final_comparison/summarization/rag/rag_summarization_final_metrics_all_experiments.csv
==============================

,experiment_id,prompt_type,model_name,temperature,max_tokens,chunk_size_words,chunk_overlap_words,embedding_model,vector_database,retrieval_method,...,selection_completeness_score_mean,selection_completeness_score_median,selection_completeness_score_std,selection_completeness_score_min,selection_completeness_score_max,selection_final_score_mean,selection_final_score_median,selection_final_score_std,selection_final_score_min,selection_final_score_max
0,exp_s_R01_summarization_zero_shot_chromadb_lla...,zero_shot_with_rag,llama-3.1-8b-instant,0.0,700,150,30,sentence-transformers/all-MiniLM-L6-v2,ChromaDB,dense_vector_retrieval,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,exp_s_R02_summarization_zero_shot_chromadb_lla...,zero_shot_with_rag,llama-3.3-70b-versatile,0.0,700,150,30,sentence-transformers/all-MiniLM-L6-v2,ChromaDB,dense_vector_retrieval,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,exp_s_R03_summarization_zero_shot_chromadb_ope...,zero_shot_with_rag,openai/gpt-oss-120b,0.0,700,150,30,sentence-transformers/all-MiniLM-L6-v2,ChromaDB,dense_vector_retrieval,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,exp_s_R04_summarization_few_shot_chromadb_llam...,few_shot_with_rag,llama-3.1-8b-instant,0.0,700,150,30,sentence-transformers/all-MiniLM-L6-v2,ChromaDB,dense_vector_retrieval,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,exp_s_R05_summarization_few_shot_chromadb_llam...,few_shot_with_rag,llama-3.3-70b-versatile,0.0,700,150,30,sentence-transformers/all-MiniLM-L6-v2,ChromaDB,dense_vector_retrieval,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,exp_s_R06_summarization_few_shot_chromadb_open...,few_shot_with_rag,openai/gpt-oss-120b,0.0,700,150,30,sentence-transformers/all-MiniLM-L6-v2,ChromaDB,dense_vector_retrieval,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,exp_s_R07_summarization_chain_of_thought_chrom...,chain_of_thought_with_rag,llama-3.1-8b-instant,0.0,700,150,30,sentence-transformers/all-MiniLM-L6-v2,ChromaDB,dense_vector_retrieval,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,exp_s_R08_summarization_chain_of_thought_chrom...,chain_of_thought_with_rag,llama-3.3-70b-versatile,0.0,700,150,30,sentence-transformers/all-MiniLM-L6-v2,ChromaDB,dense_vector_retrieval,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,exp_s_R09_summarization_chain_of_thought_chrom...,chain_of_thought_with_rag,openai/gpt-oss-120b,0.0,700,150,30,sentence-transformers/all-MiniLM-L6-v2,ChromaDB,dense_vector_retrieval,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,exp_s_R10_summarization_style_based_chromadb_l...,style_based_with_rag,llama-3.1-8b-instant,0.0,700,150,30,sentence-transformers/all-MiniLM-L6-v2,ChromaDB,dense_vector_retrieval,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,exp_s_R11_summarization_style_based_chromadb_l...,style_based_with_rag,llama-3.3-70b-versatile,0.0,700,150,30,sentence-transformers/all-MiniLM-L6-v2,ChromaDB,dense_vector_retrieval,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,exp_s_R12_summarization_style_based_chromadb_o...,style_based_with_rag,openai/gpt-oss-120b,0.0,700,150,30,sentence-transformers/all-MiniLM-L6-v2,ChromaDB,dense_vector_retrieval,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,exp_s_R13_summarization_self_consistency_chrom...,self_consistency_with_rag,llama-3.1-8b-instant,0.0,700,150,30,sentence-transformers/all-MiniLM-L6-v2,ChromaDB,dense_vector_retrieval,...,0.9856,1.0,0.0348,0.84,1.0,0.8847,0.8844,0.0399,0.7427,0.9693
13,exp_s_R15_summarization_self_consistency_chrom...,self_consistency_with_rag,openai/gpt-oss-120b,0.0,700,150,30,sentence-transformers/all-MiniLM-L6-v2,ChromaDB,dense_vector_retrieval,...,0.9736,1.0,0.0426,0.84,1.0,0.8762,0.8778,0.0341,0.7770,0.9461
14,exp_s_R14_summarization_self_consistency_chrom...,self_consistency_with_rag,llama-3.3-70b-versatile,0.0,700,150,30,sentence-transformers/all-MiniLM-L6-v2,ChromaDB,dense_vector_retrieval,...,0.9744,1.0,0.0424,0.84,1.0,0.8836,0.8896,0.0377,0.7720,0.9646

In [1]:
# ============================================================================
# COMBINE FINAL METRICS FROM ALL EXPERIMENT FOLDERS OF ROLE_CATEGORIZATION WITH RAG
# ============================================================================
import pandas as pd
from pathlib import Path
from google.colab import drive

drive.mount('/content/drive')

PROJECT_DIR = Path("/content/drive/MyDrive/Colab Notebooks/Masters/LJMU-masters-thesis")

EXPERIMENTS_DIR = PROJECT_DIR / "outputs" / "experiments" / "role_categorization" / "with_rag"

OUTPUT_DIR = PROJECT_DIR / "outputs" / "final_comparison" / "role_categorization" / "rag"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

COMBINED_FILE = OUTPUT_DIR / "rag_rc_final_metrics_all_experiments.csv"

all_rows = []

# Loop through each experiment folder
for exp_folder in EXPERIMENTS_DIR.iterdir():

    if exp_folder.is_dir():

        # Find final metrics file inside this folder
        final_metric_files = list(exp_folder.glob("final_metrics.csv"))

        if len(final_metric_files) == 0:
            print(f"No final metrics found in: {exp_folder.name}")
            continue

        # There should be only one
        file = final_metric_files[0]

        try:
            temp_df = pd.read_csv(file)

            if len(temp_df) == 0:
                print(f"Empty file: {file}")
                continue

            row = temp_df.iloc[0].to_dict()

            # Optional: add folder name for safety/debugging
            row["experiment_folder"] = exp_folder.name

            all_rows.append(row)

            print(f"Loaded: {exp_folder.name}")

        except Exception as e:
            print(f"Failed reading {file}: {e}")

# Combine all
combined_df = pd.DataFrame(all_rows)

# Save
combined_df.to_csv(COMBINED_FILE, index=False)

print("\n==============================")
print("FINAL COMBINED FILE SAVED AT:")
print(COMBINED_FILE)
print("==============================")

display(combined_df)

Mounted at /content/drive
Loaded: exp_49
Loaded: exp_48
Loaded: exp_47
Loaded: exp_46
Loaded: exp_50
Loaded: exp_51
Loaded: exp_52
Loaded: exp_53
Loaded: exp_54
Loaded: exp_55
Loaded: exp_56
Loaded: exp_57
Loaded: exp_58
Loaded: exp_59
Loaded: exp_60

==============================
FINAL COMBINED FILE SAVED AT:
/content/drive/MyDrive/Colab Notebooks/Masters/LJMU-masters-thesis/outputs/final_comparison/role_categorization/rag/rag_rc_final_metrics_all_experiments.csv
==============================

,experiment_id,task_name,prompt_type,model_name,temperature,max_tokens,rag_used,input_type,embedding_model,chunk_size_words,...,precision_macro,recall_macro,f1_macro,precision_weighted,recall_weighted,f1_weighted,avg_retrieved_chunks,avg_top_similarity,num_taxonomy_labels,experiment_folder
0,exp_49_rc_few_shot_rag_llama-3.1-8b-instant,role_categorization,few_shot_with_rag,llama-3.1-8b-instant,0.0,700,True,retrieved_job_description_chunks,all-MiniLM-L6-v2,150,...,0.6655,0.6533,0.6187,0.6752,0.66,0.6290,2.27,0.955,13,exp_49
1,exp_48_rc_zero_shot_rag_openai_gpt-oss-120b,role_categorization,zero_shot_with_rag,openai/gpt-oss-120b,0.0,700,True,retrieved_job_description_chunks,all-MiniLM-L6-v2,150,...,0.7898,0.8319,0.7721,0.8171,0.77,0.7506,2.27,0.955,13,exp_48
2,exp_47_rc_zero_shot_rag_llama-3.3-70b-versatile,role_categorization,zero_shot_with_rag,llama-3.3-70b-versatile,0.0,700,True,retrieved_job_description_chunks,all-MiniLM-L6-v2,150,...,0.7582,0.8219,0.7577,0.7649,0.75,0.7254,2.27,0.955,13,exp_47
3,exp_46_rc_zero_shot_rag_llama_3_1_8b_instant,role_categorization,zero_shot_with_rag,llama-3.1-8b-instant,0.0,700,True,retrieved_job_description_chunks,all-MiniLM-L6-v2,150,...,0.7179,0.7996,0.7401,0.6614,0.73,0.6829,2.27,0.955,13,exp_46
4,exp_50_rc_few_shot_rag_llama-3.3-70b-versatile,role_categorization,few_shot_with_rag,llama-3.3-70b-versatile,0.0,700,True,retrieved_job_description_chunks,all-MiniLM-L6-v2,150,...,0.6887,0.7948,0.7194,0.6606,0.72,0.6790,2.27,0.955,13,exp_50
5,exp_51_rc_few_shot_rag_openai_gpt-oss-120b,role_categorization,few_shot_with_rag,openai/gpt-oss-120b,0.0,700,True,retrieved_job_description_chunks,all-MiniLM-L6-v2,150,...,0.7697,0.8241,0.7686,0.7488,0.76,0.7241,2.27,0.955,13,exp_51
6,exp_52_rc_chain_of_thought_rag_llama-3.1-8b-in...,role_categorization,chain_of_thought_with_rag,llama-3.1-8b-instant,0.0,700,True,retrieved_job_description_chunks,all-MiniLM-L6-v2,150,...,0.7621,0.7927,0.7447,0.7299,0.73,0.6948,2.27,0.955,13,exp_52
7,exp_53_rc_chain_of_thought_rag_llama-3.3-70b-v...,role_categorization,chain_of_thought_with_rag,llama-3.3-70b-versatile,0.0,700,True,retrieved_job_description_chunks,all-MiniLM-L6-v2,150,...,0.7381,0.8124,0.7448,0.7289,0.74,0.7032,2.27,0.955,13,exp_53
8,exp_54_rc_chain_of_thought_rag_openai_gpt-oss-...,role_categorization,chain_of_thought_with_rag,openai/gpt-oss-120b,0.0,700,True,retrieved_job_description_chunks,all-MiniLM-L6-v2,150,...,0.7273,0.8085,0.7444,0.7073,0.73,0.6991,2.27,0.955,13,exp_54
9,exp_55_rc_style_based_rag_llama-3.1-8b-instant,role_categorization,style_based_with_rag,llama-3.1-8b-instant,0.0,700,True,retrieved_job_description_chunks,all-MiniLM-L6-v2,150,...,0.7255,0.8165,0.7500,0.6765,0.75,0.6976,2.27,0.955,13,exp_55
10,exp_56_rc_style_based_rag_llama-3.3-70b-versatile,role_categorization,style_based_with_rag,llama-3.3-70b-versatile,0.0,700,True,retrieved_job_description_chunks,all-MiniLM-L6-v2,150,...,0.7574,0.8404,0.7849,0.6996,0.78,0.7298,2.27,0.955,13,exp_56
11,exp_57_rc_style_based_rag_openai_gpt-oss-120b,role_categorization,style_based_with_rag,openai/gpt-oss-120b,0.0,700,True,retrieved_job_description_chunks,all-MiniLM-L6-v2,150,...,0.7783,0.8201,0.7810,0.7592,0.76,0.7452,2.27,0.955,13,exp_57
12,exp_58_rc_self_consistency_rag_llama-3.1-8b-in...,role_categorization,self_consistency_with_rag,llama-3.1-8b-instant,0.3,700,True,retrieved_job_description_chunks,all-MiniLM-L6-v2,150,...,0.7300,0.7780,0.7342,0.6746,0.73,0.6846,2.27,0.955,13,exp_58
13,exp_59_rc_self_consistency_rag_llama-3.3-70b-v...,role_categorization,self_consistency_with_rag,llama-3.3-70b-versatile,0.3,700,True,retrieved_job_description_chunks,all-MiniLM-L6-v2,150,...,0.6970,0.8278,0.7485,0.6684,0.76,0.7064,2.27,0.955,13,exp_59
14,exp_60_rc_self_consistency_rag_openai_gpt-oss-...,role_categorization,self_consistency_with_rag,openai/gpt-oss-120b,0.3,700,True,retrieved_job_description_chunks,all-MiniLM-L6-v2,150,...,0.7999,0.8396,0.7979,0.7744,0.78,0.7559,2.27,0.955,13,exp_60

In [2]:
# ============================================================================
# COMBINE FINAL METRICS FROM ALL EXPERIMENT FOLDERS OF ROLE_CATEGORIZATION WITHOUT RAG
# ============================================================================
import pandas as pd
from pathlib import Path
from google.colab import drive

drive.mount('/content/drive')

PROJECT_DIR = Path("/content/drive/MyDrive/Colab Notebooks/Masters/LJMU-masters-thesis")

EXPERIMENTS_DIR = PROJECT_DIR / "outputs" / "experiments" / "role_categorization" / "without_rag"

OUTPUT_DIR = PROJECT_DIR / "outputs" / "final_comparison" / "role_categorization" / "non_rag"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

COMBINED_FILE = OUTPUT_DIR / "nonrag_rc_final_metrics_all_experiments.csv"

all_rows = []

# Loop through each experiment folder
for exp_folder in EXPERIMENTS_DIR.iterdir():

    if exp_folder.is_dir():

        # Find final metrics file inside this folder
        final_metric_files = list(exp_folder.glob("final_metrics.csv"))

        if len(final_metric_files) == 0:
            print(f"No final metrics found in: {exp_folder.name}")
            continue

        # There should be only one
        file = final_metric_files[0]

        try:
            temp_df = pd.read_csv(file)

            if len(temp_df) == 0:
                print(f"Empty file: {file}")
                continue

            row = temp_df.iloc[0].to_dict()

            # Optional: add folder name for safety/debugging
            row["experiment_folder"] = exp_folder.name

            all_rows.append(row)

            print(f"Loaded: {exp_folder.name}")

        except Exception as e:
            print(f"Failed reading {file}: {e}")

# Combine all
combined_df = pd.DataFrame(all_rows)

# Save
combined_df.to_csv(COMBINED_FILE, index=False)

print("\n==============================")
print("FINAL COMBINED FILE SAVED AT:")
print(COMBINED_FILE)
print("==============================")

display(combined_df)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Loaded: exp_31
Loaded: exp_32
Loaded: exp_33
Loaded: exp_34
Loaded: exp_35
Loaded: exp_36
Loaded: exp_37
Loaded: exp_38
Loaded: exp_39
Loaded: exp_40
Loaded: exp_41
Loaded: exp_42
Loaded: exp_44
Loaded: exp_45
Loaded: exp_43

==============================
FINAL COMBINED FILE SAVED AT:
/content/drive/MyDrive/Colab Notebooks/Masters/LJMU-masters-thesis/outputs/final_comparison/role_categorization/non_rag/nonrag_rc_final_metrics_all_experiments.csv
==============================

,experiment_id,task_name,prompt_type,model_name,temperature,max_tokens,rag_used,input_type,num_samples_completed,num_correct,...,accuracy,precision_macro,recall_macro,f1_macro,precision_weighted,recall_weighted,f1_weighted,num_taxonomy_labels,experiment_folder,num_self_consistency_runs
0,exp_31_rc_zero_shot_nonrag_llama_3_1_8b_instant,role_categorization,zero_shot_without_rag,llama-3.1-8b-instant,0.0,700,False,job_description_only,100,60,...,0.60,0.5896,0.6688,0.5869,0.5672,0.60,0.5570,13,exp_31,NaN
1,exp_32_rc_zero_shot_nonrag_llama-3.3-70b-versa...,role_categorization,zero_shot_without_rag,llama-3.3-70b-versatile,0.0,700,False,job_description_only,100,66,...,0.66,0.6804,0.7693,0.6875,0.6739,0.66,0.6373,13,exp_32,NaN
2,exp_33_rc_zero_shot_nonrag_openai_gpt-oss-120b,role_categorization,zero_shot_without_rag,openai/gpt-oss-120b,0.0,700,False,job_description_only,100,70,...,0.70,0.7418,0.7720,0.7331,0.7267,0.70,0.6980,13,exp_33,NaN
3,exp_34_rc_few_shot_nonrag_llama_3_1_8b_instant,role_categorization,few_shot_without_rag,llama-3.1-8b-instant,0.0,700,False,job_description_only,100,60,...,0.60,0.6122,0.6801,0.6099,0.6135,0.60,0.5893,13,exp_34,NaN
4,exp_35_rc_few_shot_nonrag_llama-3.3-70b-versatile,role_categorization,few_shot_without_rag,llama-3.3-70b-versatile,0.0,700,False,job_description_only,100,66,...,0.66,0.6621,0.7663,0.6824,0.6254,0.66,0.6222,13,exp_35,NaN
5,exp_36_rc_few_shot_nonrag_openai_gpt-oss-120b,role_categorization,few_shot_without_rag,openai/gpt-oss-120b,0.0,700,False,job_description_only,100,70,...,0.70,0.7131,0.7873,0.7146,0.7246,0.70,0.6787,13,exp_36,NaN
6,exp_37_rc_cot_nonrag_llama_3_1_8b_instant,role_categorization,chain_of_thought_without_rag,llama-3.1-8b-instant,0.0,700,False,job_description_only,100,60,...,0.60,0.5912,0.6958,0.5965,0.5831,0.60,0.5704,13,exp_37,NaN
7,exp_38_rc_cot_nonrag_llama-3.3-70b-versatile,role_categorization,chain_of_thought_without_rag,llama-3.3-70b-versatile,0.0,700,False,job_description_only,100,66,...,0.66,0.6492,0.7683,0.6809,0.6096,0.66,0.6179,13,exp_38,NaN
8,exp_39_rc_cot_nonrag_openai_gpt-oss-120b,role_categorization,chain_of_thought_without_rag,openai/gpt-oss-120b,0.0,700,False,job_description_only,100,70,...,0.70,0.7462,0.7810,0.7083,0.7672,0.70,0.6681,13,exp_39,NaN
9,exp_40_rc_style_based_nonrag_llama_3_1_8b_instant,role_categorization,style_based_without_rag,llama-3.1-8b-instant,0.0,700,False,job_description_only,100,54,...,0.54,0.5521,0.6339,0.5186,0.5492,0.54,0.5070,13,exp_40,NaN
10,exp_41_rc_style_based_nonrag_llama-3.3-70b-ver...,role_categorization,style_based_without_rag,llama-3.3-70b-versatile,0.0,700,False,job_description_only,100,68,...,0.68,0.6830,0.7699,0.6991,0.6321,0.68,0.6376,13,exp_41,NaN
11,exp_42_rc_style_based_nonrag_openai_gpt-oss-120b,role_categorization,style_based_without_rag,openai/gpt-oss-120b,0.0,700,False,job_description_only,100,70,...,0.70,0.7478,0.7855,0.7118,0.7671,0.70,0.6680,13,exp_42,NaN
12,exp_44_rc_self_consistency_nonrag_llama-3.3-70...,role_categorization,self_consistency_without_rag,llama-3.3-70b-versatile,0.3,700,False,job_description_only,100,66,...,0.66,0.6420,0.7674,0.6746,0.6131,0.66,0.6188,13,exp_44,5.0
13,exp_45_rc_self_consistency_nonrag_openai_gpt-o...,role_categorization,self_consistency_without_rag,openai/gpt-oss-120b,0.3,700,False,job_description_only,100,72,...,0.72,0.7550,0.7954,0.7280,0.7788,0.72,0.6958,13,exp_45,5.0
14,exp_43_rc_self_consistency_nonrag_llama_3_1_8b...,role_categorization,self_consistency_without_rag,llama-3.1-8b-instant,0.3,700,False,job_description_only,100,58,...,0.58,0.5717,0.6975,0.5898,0.5680,0.58,0.5570,13,exp_43,5.0