# ================================================================
# SUMMARISATION EXPERIMENT (NON-RAG) — FEW-SHOT PROMPTING
# ================================================================

## Objective
This experiment evaluates the ability of a Large Language Model (LLM) to generate structured summaries of job descriptions using Few-Shot Prompting without Retrieval-Augmented Generation (RAG).

The experiment is designed to measure how well the LLM summarises job descriptions using only the original input text, without external retrieval or additional context.

---

## Dataset
- Source: Djinni Job Descriptions Dataset
- Dataset version:
  - `djinni_with_reference_summaries.csv`
- Sample size: All records with valid reference summaries

### Columns Used
- `Long Description` → Input job description
- `Reference_Summary` → Ground-truth reference summary
- `Position` → Original job title
- `id` → Unique identifier

---

## Experimental Setup

### Summarisation Approach
- Approach Type: Few-Shot Prompting
- Retrieval: Not used
- RAG: Not used
- Vector Database: Not used
- LLM:
  - `llama-3.3-70b-versatile` using Groq

### Generation Parameters
- Temperature: `0.0`
- Max Tokens: `700`

### Embedding Model for Evaluation
- `sentence-transformers/all-MiniLM-L6-v2`

The embedding model is used only for semantic similarity evaluation and not for generating summaries.

---

## Prompting Strategy

A fixed few-shot prompt is used for all job descriptions.

The prompt instructs the LLM to generate a concise structured summary using only information explicitly present in the job description.

The generated summary must contain exactly five sections:

- Role Overview
- Responsibilities
- Skills
- Tools
- Experience

---

## Methodology

The experiment follows these steps:

1. Load the processed Djinni dataset with reference summaries
2. Clean and preprocess job descriptions
3. Remove invalid or duplicate records
4. Keep only rows with valid reference summaries
5. Build a few-shot summarisation prompt for each job description
6. Send the prompt to the LLM
7. Capture the generated structured summary
8. Compare the generated summary with the reference summary
9. Compute automatic evaluation metrics
10. Save results and final summary metrics

---

## Evaluation Metrics

### Core Metrics
- ROUGE-L Precision
- ROUGE-L Recall
- ROUGE-L F1
- Semantic Similarity
- Compression Ratio

### Skill Preservation Metrics
- IRR (Information Retention Ratio)
- Hallucination Rate
- Top-K Skill Coverage
- Global Skill Overlap
- Hallucination Prevalence
- Hallucination Density

### Output Format Validation
The notebook also checks whether the generated summary contains all required sections:

- Role Overview
- Responsibilities
- Skills
- Tools
- Experience

---

## Outputs

The experiment generates the following output files:

### Intermediate Outputs
- `results.csv`
- `results.json`
- `failed_results.csv`

### Final Outputs
- `final_metrics.csv`
- `final_metrics.json`


---

## Purpose

This experiment serves as the baseline non-RAG summarisation experiment using Few-Shot Prompting.

In [ ]:
# ================================================================
# INSTALL REQUIRED LIBRARIES
# ================================================================
# ================================================================
# INSTALL REQUIRED LIBRARIES (RUN ONCE PER SESSION)
# ================================================================
!pip install -q pandas numpy rouge-score sentence-transformers scikit-learn groq tenacity tqdm
print("=" * 60)
print("Required Libraries installed")

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.3/142.3 kB 4.3 MB/s eta 0:00:00
  Building wheel for rouge-score (setup.py) ... done
============================================================
Required Libraries installed

In [ ]:
# ================================================================
# 1. BASIC PYTHON LIBRARIES
# ================================================================
import os
import re
import json
import warnings
import importlib.metadata
from pathlib import Path

import numpy as np
import pandas as pd

from tqdm.auto import tqdm

warnings.filterwarnings("ignore")

# ================================================================
# 2. NLP / EVALUATION LIBRARIES
# ================================================================
from rouge_score import rouge_scorer
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# ================================================================
# 3. LLM LIBRARIES
# ================================================================
from groq import Groq, RateLimitError
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type

# ================================================================
# 4. GOOGLE COLAB / DRIVE
# ================================================================
from google.colab import drive, userdata

# ================================================================
# 5. VERSION CHECKS
# ================================================================
def get_version(pkg):
    try:
        return importlib.metadata.version(pkg)
    except Exception:
        return "installed"

print("=" * 60)
print("LIBRARY VERSION CHECK")
print("=" * 60)
print("pandas               :", pd.__version__)
print("numpy                :", np.__version__)
print("rouge-score          :", get_version("rouge-score"))
print("sentence-transformers:", get_version("sentence-transformers"))
print("groq                 :", get_version("groq"))
print("=" * 60)

# ================================================================
# 6. MOUNT GOOGLE DRIVE
# ================================================================
drive.mount('/content/drive')

# Root project directory in Google Drive
PROJECT_DIR = Path("/content/drive/MyDrive/Colab Notebooks/Masters/Masters_Thesis_Project")
PROJECT_DIR.mkdir(parents=True, exist_ok=True)

print("Project directory:", PROJECT_DIR)

# ================================================================
# 7. LOAD GROQ API KEY
# ================================================================
# Make sure GROQ_API_KEY exists in Colab Secrets
GROQ_API_KEY = userdata.get("GROQ_API_KEY_1")
assert GROQ_API_KEY, "GROQ_API_KEY is missing in Colab Secrets."

os.environ["GROQ_API_KEY"] = GROQ_API_KEY
print("GROQ API key loaded from Colab secrets")

# ================================================================
# 8. EXPERIMENT CONFIGURATION
# ================================================================
# File paths
PROCESSED_DATA_DIR = PROJECT_DIR / "data" / "reference_summaries"
REFERENCE_DATASET_PATH = PROCESSED_DATA_DIR / "djinni_with_reference_summaries.csv"

# Column names
TEXT_COLUMN = "Long Description"
ID_COLUMN = "id"
POSITION_COLUMN = "Position"
REFERENCE_SUMMARY_COLUMN = "Reference_Summary"

# Experiment settings
EXPERIMENT_ID = "exp_s_05_few_shot_without_rag_llama-3.3-70b-versatile"
PROMPT_TYPE = "few_shot"
MODEL_NAME = "llama-3.3-70b-versatile"
TEMPERATURE = 0.0
MAX_TOKENS = 700

# Embedding model for semantic similarity
EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"

# Output paths
OUTPUT_DIR = PROJECT_DIR / "outputs" / "experiments" / EXPERIMENT_ID
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

BATCH_RESULTS_JSON = OUTPUT_DIR / f"{EXPERIMENT_ID}.json"
BATCH_RESULTS_CSV = OUTPUT_DIR / f"{EXPERIMENT_ID}.csv"
FAILED_RESULTS_CSV = OUTPUT_DIR / f"{EXPERIMENT_ID}_failed.csv"

print("Experiment ID :", EXPERIMENT_ID)
print("Model         :", MODEL_NAME)
print("Temperature   :", TEMPERATURE)
print("Max tokens    :", MAX_TOKENS)
print("Reference CSV :", REFERENCE_DATASET_PATH)
print("Output dir    :", OUTPUT_DIR)

# ================================================================
# 9. LOAD DATASET FROM CSV WITH REFERENCE SUMMARIES
# ================================================================
# IMPORTANT:
# We are NOT loading the raw Hugging Face dataset here.
# We are loading the processed CSV that already contains Reference_Summary.
print("=" * 60)
print("Loading processed dataset with reference summaries...")

df = pd.read_csv(REFERENCE_DATASET_PATH)

print("=" * 60)
print("Dataset loaded successfully")
print("Shape   :", df.shape)
print("Columns :", list(df.columns))

display(df.head(3))
print("=" * 60)

# ================================================================
# 10. DATA CLEANING / PREPROCESSING
# ================================================================
def clean_text(text: str) -> str:
    """
    Clean noisy job description text.
    """
    if pd.isna(text):
        return ""

    text = str(text)

    # Remove HTML tags if any
    text = re.sub(r"<[^>]+>", " ", text)

    # Remove URLs if any
    text = re.sub(r"http\S+|www\S+", " ", text)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text


def preprocess_dataset(df: pd.DataFrame, text_column: str, id_column: str) -> pd.DataFrame:
    """
    Remove null, duplicate, and noisy records.
    """
    work_df = df.copy()

    # Keep only rows with valid text and id
    work_df = work_df[work_df[text_column].notna()]
    work_df = work_df[work_df[id_column].notna()]

    # Clean text
    work_df[text_column] = work_df[text_column].apply(clean_text)

    # Remove empty records after cleaning
    work_df = work_df[work_df[text_column].str.strip().ne("")]

    # Remove duplicate Long Description entries
    work_df = work_df.drop_duplicates(subset=[text_column]).reset_index(drop=True)

    return work_df


clean_df = preprocess_dataset(
    df=df,
    text_column=TEXT_COLUMN,
    id_column=ID_COLUMN
)

print("Original shape :", df.shape)
print("Cleaned shape  :", clean_df.shape)

display(clean_df[[ID_COLUMN, POSITION_COLUMN, TEXT_COLUMN]].head(3))

# ================================================================
# 11. FILTER ROWS WITH REFERENCE SUMMARIES
# ================================================================
if REFERENCE_SUMMARY_COLUMN not in clean_df.columns:
    raise ValueError(f"{REFERENCE_SUMMARY_COLUMN} column not found in dataset.")

# Standardize Reference_Summary column
clean_df[REFERENCE_SUMMARY_COLUMN] = clean_df[REFERENCE_SUMMARY_COLUMN].fillna("").astype(str)

# Convert literal 'nan' strings to empty
clean_df.loc[
    clean_df[REFERENCE_SUMMARY_COLUMN].str.strip().str.lower() == "nan",
    REFERENCE_SUMMARY_COLUMN
] = ""

# Keep only rows that already have reference summaries
valid_df = clean_df[
    clean_df[REFERENCE_SUMMARY_COLUMN].str.strip().ne("")
].copy()

print("Rows with reference summaries:", len(valid_df))

# Run on 10 samples first
experiment_df = valid_df.copy().reset_index(drop=True)

print("Experiment rows selected:", len(experiment_df))
print("=" * 60)
display(experiment_df[[ID_COLUMN, POSITION_COLUMN]].head(10))

# ================================================================
# 12. PROMPT FUNCTION
# ================================================================
def build_few_shot_prompt(job_description: str) -> str:
    return f"""
You are an expert HR analyst.

Below are examples of how to summarize job descriptions.

Example 1:

Job Description:
We are looking for a backend developer with experience in Java, Spring Boot, and Microservices. The candidate should work on REST APIs and collaborate with cross-functional teams. Knowledge of Docker and AWS is preferred. Minimum 3 years of experience required.

Summary:

Role Overview:
Backend developer responsible for building scalable APIs.

Responsibilities:
Develop REST APIs and collaborate with teams.

Skills:
Java, Spring Boot, Microservices

Tools:
Docker, AWS

Experience:
3+ years


Example 2:

Job Description:
Seeking a data analyst skilled in Python, SQL, and Tableau. The role involves data cleaning, visualization, and reporting insights to stakeholders. Experience in Excel and communication skills are required.

Summary:

Role Overview:
Data analyst focused on deriving insights from data.

Responsibilities:
Analyze data and create reports for stakeholders.

Skills:
Python, SQL, Tableau

Tools:
Excel

Experience:
Not explicitly stated


Now summarize the following job description in the SAME format.

Rules:
- Use only information from the text
- Do not add new information
- Keep it concise
- Skills and Tools must be comma-separated
- If missing, write: Not explicitly stated
- Do not include reasoning

Job Description:
{job_description}
""".strip()


# ================================================================
# 13. GROQ CLIENT
# ================================================================
class LLMClientError(Exception):
    """
    Custom error for LLM failures.
    """
    pass


class GroqClient:
    """
    Groq client wrapper for summarisation experiments.
    """

    def __init__(self, model_name: str):
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            raise ValueError("GROQ_API_KEY is missing from environment variables.")
        self.client = Groq(api_key=api_key)
        self.model_name = model_name

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=1, min=2, max=10),
        retry=retry_if_exception_type(Exception),
        reraise=True
    )
    def generate(
        self,
        prompt: str,
        temperature: float,
        max_tokens: int
    ) -> str:
        completion = self.client.chat.completions.create(
            model=self.model_name,
            messages=[
                {"role": "system", "content": "You are a precise and factual HR summarisation assistant."},
                {"role": "user", "content": prompt},
            ],
            temperature=temperature,
            max_tokens=max_tokens,
        )

        if not completion.choices:
            raise LLMClientError("Groq returned no choices.")

        text = completion.choices[0].message.content
        if not text or not str(text).strip():
            raise LLMClientError("Groq returned an empty response.")

        return str(text).strip()


groq_client = GroqClient(model_name=MODEL_NAME)
print("Groq client initialized")


# ================================================================
# 14. EVALUATION FUNCTIONS
# ================================================================
_embedding_model_cache = {}

def get_embedding_model(model_name: str):
    """
    Cache embedding model so it loads only once.
    """
    if model_name not in _embedding_model_cache:
        _embedding_model_cache[model_name] = SentenceTransformer(model_name)
    return _embedding_model_cache[model_name]


def compute_rouge_l(reference_text: str, generated_text: str):
    """
    Compute ROUGE-L precision, recall, and F1.
    """
    scorer = rouge_scorer.RougeScorer(["rougeL"], use_stemmer=True)
    score = scorer.score(reference_text, generated_text)["rougeL"]
    return {
        "rougeL_precision": round(score.precision, 4),
        "rougeL_recall": round(score.recall, 4),
        "rougeL_f1": round(score.fmeasure, 4),
    }


def compute_semantic_similarity(reference_text: str, generated_text: str, embedding_model_name: str):
    """
    Compute semantic similarity using sentence embeddings.
    """
    model = get_embedding_model(embedding_model_name)
    embeddings = model.encode([reference_text, generated_text], convert_to_numpy=True)
    similarity = cosine_similarity([embeddings[0]], [embeddings[1]])[0][0]
    return round(float(similarity), 4)


def compute_compression_ratio(original_text: str, summary_text: str):
    """
    Compression ratio = summary length / original JD length
    """
    original_length = max(len(original_text.split()), 1)
    summary_length = len(summary_text.split())
    return round(summary_length / original_length, 4)


def validate_experiment_summary_sections(summary_text: str):
    """
    Check whether required output sections are present.
    """
    required_sections = [
        "Role Overview",
        "Responsibilities",
        "Skills",
        "Tools",
        "Experience",
    ]
    lowered = str(summary_text).lower()
    return {
        section: f"{section.lower()}:" in lowered
        for section in required_sections
    }


# ================================================================
# 15. SKILL EXTRACTION AND CUSTOM METRICS
# ================================================================
def normalize_skill(text: str) -> str:
    """
    Normalize extracted skill phrase.
    """
    text = str(text).strip().lower()
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"^[,;:\-\.\s]+|[,;:\-\.\s]+$", "", text)
    return text


def extract_skills(text: str):
    """
    Extract explicitly mentioned skills without using a predefined skill lexicon.

    Strategy:
    1. Capture phrases after common skill-introducing patterns
    2. Split multi-skill phrases by commas / and / slash
    3. Capture likely capitalized technical terms
    4. Normalize and deduplicate
    """
    if not text or not isinstance(text, str):
        return []

    text = re.sub(r"\s+", " ", text).strip()
    extracted = []

    patterns = [
        r"(?:experience with|experience in|proficient in|proficiency in|knowledge of|familiarity with|expertise in|skills in|skilled in)\s+([A-Za-z0-9\+\#\./,\-\s]+?)(?:\.|;|:|, and| and |\n|$)",
        r"(?:tools?:|technologies:|skills:)\s*([A-Za-z0-9\+\#\./,\-\s]+?)(?:\.|\n|$)",
        r"(?:requirements?:|required skills:)\s*([A-Za-z0-9\+\#\./,\-\s]+?)(?:\.|\n|$)",
    ]

    for pattern in patterns:
        matches = re.findall(pattern, text, flags=re.IGNORECASE)
        for match in matches:
            parts = re.split(r",| and |/|\|", match)
            for part in parts:
                skill = normalize_skill(part)
                if skill and len(skill) > 1:
                    extracted.append(skill)

    tech_terms = re.findall(
        r"\b(?:[A-Z][A-Za-z0-9\+\#\.]{1,}|[A-Za-z]+\+[A-Za-z]+|[A-Za-z]+#[A-Za-z]+)\b",
        text
    )
    for term in tech_terms:
        skill = normalize_skill(term)
        if skill and len(skill) > 1:
            extracted.append(skill)

    blacklist = {
        "experience",
        "skills",
        "tools",
        "technologies",
        "knowledge",
        "familiarity",
        "expertise",
        "requirements",
        "required skills",
    }

    extracted = [s for s in extracted if s not in blacklist]

    return sorted(list(set(extracted)))


def build_skill_analysis(original_text: str, summary_text: str):
    """
    Extract skills from original JD and generated summary.
    Then compute IRR and hallucinated skills.
    """
    jd_skills = extract_skills(original_text)
    summary_skills = extract_skills(summary_text)

    jd_set = set(map(normalize_skill, jd_skills))
    summary_set = set(map(normalize_skill, summary_skills))

    irr = len(jd_set & summary_set) / len(jd_set) if len(jd_set) > 0 else 0.0
    hallucinated_skills = sorted(list(summary_set - jd_set))

    return {
        "jd_skills": sorted(list(jd_set)),
        "summary_skills": sorted(list(summary_set)),
        "irr": round(irr, 4),
        "hallucinated_skills": hallucinated_skills,
    }


def compute_hallucination_rate(original_skills, summary_skills):
    """
    Hallucination rate = hallucinated skills / total summary skills
    """
    original_set = set(map(normalize_skill, original_skills))
    summary_set = set(map(normalize_skill, summary_skills))

    if len(summary_set) == 0:
        return 0.0

    hallucinated = summary_set - original_set
    return round(len(hallucinated) / len(summary_set), 4)


def compute_top_k_skill_coverage(original_skills, summary_skills, k=5):
    """
    Top-K skill coverage = overlap of first K JD skills with summary skills.
    """
    original_top_k = list(original_skills)[:k]
    original_set = set(map(normalize_skill, original_top_k))
    summary_set = set(map(normalize_skill, summary_skills))

    if len(original_set) == 0:
        return 0.0

    return round(len(original_set & summary_set) / len(original_set), 4)




# ================================================================
# 16. CHECKPOINT / RESUME
# ================================================================
if BATCH_RESULTS_JSON.exists():
    with open(BATCH_RESULTS_JSON, "r", encoding="utf-8") as f:
        loaded = json.load(f)

    if isinstance(loaded, list):
        all_results = loaded
        completed_ids = {str(r["selected_id"]) for r in all_results if "selected_id" in r}
    else:
        all_results = []
        completed_ids = set()
else:
    all_results = []
    completed_ids = set()

failed_results = []
if FAILED_RESULTS_CSV.exists():
    try:
        failed_results = pd.read_csv(FAILED_RESULTS_CSV).to_dict(orient="records")
    except Exception:
        failed_results = []

print("Already completed:", len(completed_ids))
print("Already failed   :", len(failed_results))

for r in all_results:
    if "prompt_type" not in r:
        r["prompt_type"] = PROMPT_TYPE


# ================================================================
# 17. CHECKPOINT SAVE FUNCTION
# ================================================================
def save_checkpoints(all_results, failed_results):
    """
    Save current successful results and failed records.
    """
    with open(BATCH_RESULTS_JSON, "w", encoding="utf-8") as f:
        json.dump(all_results, f, indent=2, ensure_ascii=False)

    if all_results:
        checkpoint_df = pd.DataFrame(all_results).copy()

        for col in ["jd_skills", "summary_skills", "hallucinated_skills", "section_validation"]:
            if col in checkpoint_df.columns:
                checkpoint_df[col] = checkpoint_df[col].apply(
                    lambda x: json.dumps(x, ensure_ascii=False)
                )

        checkpoint_df.to_csv(BATCH_RESULTS_CSV, index=False, encoding="utf-8")

    if failed_results:
        pd.DataFrame(failed_results).to_csv(FAILED_RESULTS_CSV, index=False, encoding="utf-8")




# ================================================================
# 18. RUN EXPERIMENT ON 100 RECORDS
# ================================================================
for i, row in tqdm(
    experiment_df.iterrows(),
    total=len(experiment_df),
    desc="Running Summarization Experiment",
    unit="JD"
):
    current_id = str(row[ID_COLUMN])

    if current_id in completed_ids:
        tqdm.write(f"Skipped {i+1}/{len(experiment_df)} | ID: {current_id}")
        continue

    tqdm.write(f"Running {i+1}/{len(experiment_df)} | ID: {current_id}")

    try:
        job_description = row[TEXT_COLUMN]
        reference_summary = row[REFERENCE_SUMMARY_COLUMN]

        prompt = build_few_shot_prompt(job_description=job_description)

        generated_summary = groq_client.generate(
            prompt=prompt,
            temperature=TEMPERATURE,
            max_tokens=MAX_TOKENS
        )

        rouge_scores = compute_rouge_l(reference_summary, generated_summary)

        semantic_similarity = compute_semantic_similarity(
            reference_text=reference_summary,
            generated_text=generated_summary,
            embedding_model_name=EMBEDDING_MODEL_NAME
        )

        compression_ratio = compute_compression_ratio(
            original_text=job_description,
            summary_text=generated_summary
        )

        skill_analysis = build_skill_analysis(
            original_text=job_description,
            summary_text=generated_summary
        )

        hallucination_rate = compute_hallucination_rate(
            original_skills=skill_analysis["jd_skills"],
            summary_skills=skill_analysis["summary_skills"]
        )

        top_k_skill_coverage = compute_top_k_skill_coverage(
            original_skills=skill_analysis["jd_skills"],
            summary_skills=skill_analysis["summary_skills"],
            k=5
        )

        section_validation = validate_experiment_summary_sections(
            generated_summary
        )

        result = {
            "experiment_id": EXPERIMENT_ID,
            "selected_id": current_id,
            "prompt_type": PROMPT_TYPE,
            "model_name": MODEL_NAME,
            "temperature": TEMPERATURE,
            "max_tokens": MAX_TOKENS,
            "job_description": job_description,
            "reference_summary": reference_summary,
            "generated_summary": generated_summary,
            **rouge_scores,
            "semantic_similarity": semantic_similarity,
            "compression_ratio": compression_ratio,
            "jd_skills": skill_analysis["jd_skills"],
            "summary_skills": skill_analysis["summary_skills"],
            "irr": skill_analysis["irr"],
            "hallucinated_skills": skill_analysis["hallucinated_skills"],
            "hallucination_rate": hallucination_rate,
            "top_k_skill_coverage": top_k_skill_coverage,
            "section_validation": section_validation,
        }

        all_results.append(result)
        completed_ids.add(current_id)

        save_checkpoints(all_results, failed_results)

        tqdm.write(
            f"Completed {i+1}/{len(experiment_df)} | "
            f"ID: {current_id} | "
            f"ROUGE-L: {result['rougeL_f1']} | "
            f"Sim: {result['semantic_similarity']} | "
            f"IRR: {result['irr']}"
        )

    except RateLimitError as e:
        tqdm.write("Rate limit hit. Checkpoint saved.")
        tqdm.write(str(e))
        save_checkpoints(all_results, failed_results)
        break

    except Exception as e:
        tqdm.write(
            f"Failed {i+1}/{len(experiment_df)} | "
            f"ID: {current_id} | Error: {e}"
        )

        failed_results.append({
            "selected_id": current_id,
            "error": str(e)
        })

        save_checkpoints(all_results, failed_results)
        continue



# ================================================================
# 19. FINAL SUMMARY METRICS AND SAVE SEPARATE CSV
# ================================================================
results_df = pd.DataFrame(all_results)

FINAL_METRICS_CSV = OUTPUT_DIR / f"{EXPERIMENT_ID}_final_metrics.csv"
FINAL_METRICS_JSON = OUTPUT_DIR / f"{EXPERIMENT_ID}_final_metrics.json"

print("Saved JSON to:", BATCH_RESULTS_JSON)
print("Saved CSV to :", BATCH_RESULTS_CSV)

METRIC_COLUMNS = [
    "rougeL_f1",
    "semantic_similarity",
    "irr",
    "hallucination_rate",
    "compression_ratio",
    "top_k_skill_coverage",
]

def compute_global_skill_overlap(results_df):
    all_jd_skills = set()
    all_summary_skills = set()

    for _, row in results_df.iterrows():
        jd_skills = row["jd_skills"]
        summary_skills = row["summary_skills"]

        if isinstance(jd_skills, list):
            all_jd_skills.update(jd_skills)

        if isinstance(summary_skills, list):
            all_summary_skills.update(summary_skills)

    if len(all_jd_skills) == 0:
        return 0.0

    overlap = all_jd_skills & all_summary_skills
    return round(len(overlap) / len(all_jd_skills), 4)


def compute_hallucination_prevalence(results_df):
    hallucinated_count = results_df["hallucinated_skills"].apply(
        lambda x: len(x) if isinstance(x, list) else 0
    )

    summaries_with_hallucination = (hallucinated_count > 0).sum()
    total_summaries = len(results_df)

    prevalence = summaries_with_hallucination / total_summaries if total_summaries > 0 else 0.0

    affected = hallucinated_count[hallucinated_count > 0]
    density = affected.mean() if len(affected) > 0 else 0.0

    return round(prevalence, 4), round(density, 4)


if not results_df.empty:
    final_metrics = {
        "experiment_id": EXPERIMENT_ID,
        "prompt_type": PROMPT_TYPE,
        "model_name": MODEL_NAME,
        "temperature": TEMPERATURE,
        "max_tokens": MAX_TOKENS,
        "num_samples_completed": len(results_df),
    }

    for metric in METRIC_COLUMNS:
        final_metrics[f"{metric}_mean"] = round(results_df[metric].mean(), 4)
        final_metrics[f"{metric}_median"] = round(results_df[metric].median(), 4)
        final_metrics[f"{metric}_std"] = round(results_df[metric].std(), 4)
        final_metrics[f"{metric}_min"] = round(results_df[metric].min(), 4)
        final_metrics[f"{metric}_max"] = round(results_df[metric].max(), 4)

    global_skill_overlap = compute_global_skill_overlap(results_df)
    hallucination_prevalence, hallucination_density = compute_hallucination_prevalence(results_df)

    final_metrics["global_skill_overlap"] = global_skill_overlap
    final_metrics["hallucination_prevalence"] = hallucination_prevalence
    final_metrics["hallucination_density"] = hallucination_density

    final_metrics_df = pd.DataFrame([final_metrics])
    final_metrics_df.to_csv(FINAL_METRICS_CSV, index=False, encoding="utf-8")

    print("\n===== FINAL SUMMARY METRICS =====")
    print("ROUGE-L Mean:", final_metrics["rougeL_f1_mean"])
    print("ROUGE-L Median:", final_metrics["rougeL_f1_median"])
    print("ROUGE-L Std:", final_metrics["rougeL_f1_std"])

    print("Semantic Similarity Mean:", final_metrics["semantic_similarity_mean"])
    print("IRR Mean:", final_metrics["irr_mean"])
    print("Global Skill Overlap:", final_metrics["global_skill_overlap"])

    print("Hallucination Rate Mean:", final_metrics["hallucination_rate_mean"])
    print("Hallucination Prevalence:", final_metrics["hallucination_prevalence"])
    print("Hallucination Density:", final_metrics["hallucination_density"])

    print("Compression Ratio Mean:", final_metrics["compression_ratio_mean"])
    print("Top-K Skill Coverage Mean:", final_metrics["top_k_skill_coverage_mean"])

    print("\nSaved final metrics to:", FINAL_METRICS_CSV)

    # Save JSON
    with open(FINAL_METRICS_JSON, "w", encoding="utf-8") as f:
      json.dump(final_metrics, f, indent=4, ensure_ascii=False)

    print("Saved final metrics JSON to:", FINAL_METRICS_JSON)

    display(final_metrics_df)
else:
    print("No results available yet.")

============================================================
LIBRARY VERSION CHECK
============================================================
pandas               : 2.2.2
numpy                : 2.0.2
rouge-score          : 0.1.2
sentence-transformers: 5.4.0
groq                 : 1.2.0
============================================================
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Project directory: /content/drive/MyDrive/Colab Notebooks/Masters/Masters_Thesis_Project
GROQ API key loaded from Colab secrets
Experiment ID : exp_s_05_few_shot_without_rag_llama-3.3-70b-versatile
Model         : llama-3.3-70b-versatile
Temperature   : 0.0
Max tokens    : 700
Reference CSV : /content/drive/MyDrive/Colab Notebooks/Masters/Masters_Thesis_Project/data/reference_summaries/djinni_with_reference_summaries.csv
Output dir    : /content/drive/MyDrive/Colab Notebooks/Masters/Masters_Thesis_Project/outputs/experiments/exp_s_05_few_shot_without_rag_llama-3.3-70b-versatile
============================================================
Loading processed dataset with reference summaries...
============================================================
Dataset loaded successfully
Shape   : (100, 11)
Columns : ['Position', 'Long Description', 'Company Name', 'Exp Years', 'Primary Keyword', 'English Level', 'Published', 'Long Description_lang', 'id', 'index_level_0', 'Reference_Summary']

,Position,Long Description,Company Name,Exp Years,Primary Keyword,English Level,Published,Long Description_lang,id,index_level_0,Reference_Summary
0,Java Developer,The job holder will . Design develop and maint...,Quickstarter,3y,Java,upper,2021-12-01T00:00:00+02:00,en,67aefec1-1efc-5c5b-b2db-c0ef5b74f519,77261,Role Overview:\nThe Java Developer will design...
1,Integration specialist / DevOps,Project Description Join our Development Cente...,Luxoft,3y,DevOps,upper,2022-04-01T00:00:00+03:00,en,2ec599d6-1509-5c34-9aec-54ac2e04b2d5,72279,Role Overview:\nThe Integration Specialist / D...
2,Head of Marketing,TurnKey Labs is the most trusted offshore soft...,TurnKey Labs,5y,Marketing,upper,2021-10-01T00:00:00+03:00,en,edba8bfd-8a91-5b37-9f72-bde92397e804,69706,"Role Overview:\nReporting to the CEO, the Head..."

============================================================
Original shape : (100, 11)
Cleaned shape  : (100, 11)

,id,Position,Long Description
0,67aefec1-1efc-5c5b-b2db-c0ef5b74f519,Java Developer,The job holder will . Design develop and maint...
1,2ec599d6-1509-5c34-9aec-54ac2e04b2d5,Integration specialist / DevOps,Project Description Join our Development Cente...
2,edba8bfd-8a91-5b37-9f72-bde92397e804,Head of Marketing,TurnKey Labs is the most trusted offshore soft...

Rows with reference summaries: 100
Experiment rows selected: 100
============================================================

,id,Position
0,67aefec1-1efc-5c5b-b2db-c0ef5b74f519,Java Developer
1,2ec599d6-1509-5c34-9aec-54ac2e04b2d5,Integration specialist / DevOps
2,edba8bfd-8a91-5b37-9f72-bde92397e804,Head of Marketing
3,077025bf-2c32-5855-9211-68b09228a635,Project Manager
4,adb62bd6-998e-58ec-a32c-3b99fe814b04,Sales manager
5,b2315b02-ac50-551c-93b5-a88d6ee230e6,PHP Developer
6,881421a8-07a9-59a0-9765-6c48609ae879,"MERN (Node, React) JS Full-stack developer"
7,b5fc4457-65a2-51c9-92fe-b9be2fc4888c,Golang Engineer
8,bcbb5ce1-9ab8-5297-9472-791398c09e55,People Partner
9,16fcc7e5-ba83-5125-92eb-3e9cc3185261,Creative Designer

Groq client initialized
Already completed: 0
Already failed   : 0

Running Summarization Experiment:   0%|          | 0/100 [00:00<?, ?JD/s]

Running 1/100 | ID: 67aefec1-1efc-5c5b-b2db-c0ef5b74f519

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Completed 1/100 | ID: 67aefec1-1efc-5c5b-b2db-c0ef5b74f519 | ROUGE-L: 0.3947 | Sim: 0.7796 | IRR: 0.3214
Running 2/100 | ID: 2ec599d6-1509-5c34-9aec-54ac2e04b2d5
Completed 2/100 | ID: 2ec599d6-1509-5c34-9aec-54ac2e04b2d5 | ROUGE-L: 0.4955 | Sim: 0.8687 | IRR: 0.4286
Running 3/100 | ID: edba8bfd-8a91-5b37-9f72-bde92397e804
Completed 3/100 | ID: edba8bfd-8a91-5b37-9f72-bde92397e804 | ROUGE-L: 0.3365 | Sim: 0.848 | IRR: 0.0448
Running 4/100 | ID: 077025bf-2c32-5855-9211-68b09228a635
Completed 4/100 | ID: 077025bf-2c32-5855-9211-68b09228a635 | ROUGE-L: 0.4148 | Sim: 0.7322 | IRR: 0.2128
Running 5/100 | ID: adb62bd6-998e-58ec-a32c-3b99fe814b04
Completed 5/100 | ID: adb62bd6-998e-58ec-a32c-3b99fe814b04 | ROUGE-L: 0.4513 | Sim: 0.6742 | IRR: 0.3
Running 6/100 | ID: b2315b02-ac50-551c-93b5-a88d6ee230e6
Completed 6/100 | ID: b2315b02-ac50-551c-93b5-a88d6ee230e6 | ROUGE-L: 0.4865 | Sim: 0.8787 | IRR: 0.4884
Running 7/100 | ID: 881421a8-07a9-59a0-9765-6c48609ae879
Completed 7/100 | ID: 881421a8-07a9-59a0-9765-6c48609ae879 | ROUGE-L: 0.3188 | Sim: 0.7709 | IRR: 0.4375
Running 8/100 | ID: b5fc4457-65a2-51c9-92fe-b9be2fc4888c
Completed 8/100 | ID: b5fc4457-65a2-51c9-92fe-b9be2fc4888c | ROUGE-L: 0.386 | Sim: 0.7532 | IRR: 0.2558
Running 9/100 | ID: bcbb5ce1-9ab8-5297-9472-791398c09e55
Completed 9/100 | ID: bcbb5ce1-9ab8-5297-9472-791398c09e55 | ROUGE-L: 0.4019 | Sim: 0.7312 | IRR: 0.0741
Running 10/100 | ID: 16fcc7e5-ba83-5125-92eb-3e9cc3185261
Completed 10/100 | ID: 16fcc7e5-ba83-5125-92eb-3e9cc3185261 | ROUGE-L: 0.4497 | Sim: 0.8425 | IRR: 0.254
Running 11/100 | ID: 3b5c5d8b-1ce1-5268-84e4-87981716111b
Completed 11/100 | ID: 3b5c5d8b-1ce1-5268-84e4-87981716111b | ROUGE-L: 0.3636 | Sim: 0.707 | IRR: 0.2651
Running 12/100 | ID: ef401f92-f924-5ab2-bee2-f60e5f2c9dc5
Completed 12/100 | ID: ef401f92-f924-5ab2-bee2-f60e5f2c9dc5 | ROUGE-L: 0.3651 | Sim: 0.8453 | IRR: 0.1481
Running 13/100 | ID: 9f81ca91-9f9e-5295-91aa-e05a1d228556
Completed 13/100 | ID: 9f81ca91-9f9e-5295-91aa-e05a1d228556 | ROUGE-L: 0.3478 | Sim: 0.7362 | IRR: 0.2941
Running 14/100 | ID: 345fde08-2c9b-51b6-aaef-e0d10cbe15b0
Completed 14/100 | ID: 345fde08-2c9b-51b6-aaef-e0d10cbe15b0 | ROUGE-L: 0.2938 | Sim: 0.8066 | IRR: 0.3
Running 15/100 | ID: ab7a057a-1e11-560b-985d-07846b660dda
Completed 15/100 | ID: ab7a057a-1e11-560b-985d-07846b660dda | ROUGE-L: 0.4058 | Sim: 0.8591 | IRR: 0.4483
Running 16/100 | ID: 1033d838-1753-5d48-8a93-3981e34666f6
Completed 16/100 | ID: 1033d838-1753-5d48-8a93-3981e34666f6 | ROUGE-L: 0.3353 | Sim: 0.7968 | IRR: 0.2308
Running 17/100 | ID: b0cb9821-ad43-5999-9a17-dd95ec8e781a
Completed 17/100 | ID: b0cb9821-ad43-5999-9a17-dd95ec8e781a | ROUGE-L: 0.3545 | Sim: 0.7298 | IRR: 0.3043
Running 18/100 | ID: 03d5d9fe-f19b-5baa-9f80-29d3bf3cd9c7
Completed 18/100 | ID: 03d5d9fe-f19b-5baa-9f80-29d3bf3cd9c7 | ROUGE-L: 0.3881 | Sim: 0.7867 | IRR: 0.1585
Running 19/100 | ID: beacc1c0-f237-5182-b394-6c968254be79
Completed 19/100 | ID: beacc1c0-f237-5182-b394-6c968254be79 | ROUGE-L: 0.3958 | Sim: 0.8142 | IRR: 0.3023
Running 20/100 | ID: 4ebda3a8-6249-5bc8-8118-6e21be66a1de
Completed 20/100 | ID: 4ebda3a8-6249-5bc8-8118-6e21be66a1de | ROUGE-L: 0.3188 | Sim: 0.8523 | IRR: 0.3
Running 21/100 | ID: 9b343996-ce39-56ad-bed1-ccb5a41814fc
Completed 21/100 | ID: 9b343996-ce39-56ad-bed1-ccb5a41814fc | ROUGE-L: 0.3871 | Sim: 0.8771 | IRR: 0.2632
Running 22/100 | ID: 66a7dbc2-c188-5afa-a2fa-f729ef2292b2
Completed 22/100 | ID: 66a7dbc2-c188-5afa-a2fa-f729ef2292b2 | ROUGE-L: 0.3153 | Sim: 0.8132 | IRR: 0.1176
Running 23/100 | ID: 931b1048-ac7a-5a77-adeb-2006d1a44a93
Completed 23/100 | ID: 931b1048-ac7a-5a77-adeb-2006d1a44a93 | ROUGE-L: 0.2839 | Sim: 0.7972 | IRR: 0.1842
Running 24/100 | ID: f00ecb27-73a8-5456-b5cd-10f2ba7cae12
Completed 24/100 | ID: f00ecb27-73a8-5456-b5cd-10f2ba7cae12 | ROUGE-L: 0.2162 | Sim: 0.8045 | IRR: 0.3448
Running 25/100 | ID: cc8a84c0-8df5-5e44-9793-50991b3e46e2
Completed 25/100 | ID: cc8a84c0-8df5-5e44-9793-50991b3e46e2 | ROUGE-L: 0.252 | Sim: 0.7425 | IRR: 0.4082
Running 26/100 | ID: 42331ff5-ce34-5c2c-9d94-97fd9fff1515
Completed 26/100 | ID: 42331ff5-ce34-5c2c-9d94-97fd9fff1515 | ROUGE-L: 0.2886 | Sim: 0.8099 | IRR: 0.1591
Running 27/100 | ID: 8c51792f-fb89-5d0a-9515-283bf72e3246
Completed 27/100 | ID: 8c51792f-fb89-5d0a-9515-283bf72e3246 | ROUGE-L: 0.3874 | Sim: 0.7056 | IRR: 0.3276
Running 28/100 | ID: 0271807c-0658-5b23-9dd8-e5bf54e72686
Completed 28/100 | ID: 0271807c-0658-5b23-9dd8-e5bf54e72686 | ROUGE-L: 0.2798 | Sim: 0.707 | IRR: 0.1458
Running 29/100 | ID: 04b80a32-a6fc-5207-9322-59cda1d45a6f
Completed 29/100 | ID: 04b80a32-a6fc-5207-9322-59cda1d45a6f | ROUGE-L: 0.4024 | Sim: 0.8406 | IRR: 0.3846
Running 30/100 | ID: 89e75f7e-a2cb-5cb5-a3ed-01b61882b538
Completed 30/100 | ID: 89e75f7e-a2cb-5cb5-a3ed-01b61882b538 | ROUGE-L: 0.3962 | Sim: 0.8317 | IRR: 0.2
Running 31/100 | ID: faa0d662-bb50-5bed-b5e4-eda682b0fa93
Completed 31/100 | ID: faa0d662-bb50-5bed-b5e4-eda682b0fa93 | ROUGE-L: 0.3237 | Sim: 0.8295 | IRR: 0.2941
Running 32/100 | ID: 859a9003-f724-5739-9267-1a0ce13b9770
Completed 32/100 | ID: 859a9003-f724-5739-9267-1a0ce13b9770 | ROUGE-L: 0.3182 | Sim: 0.9149 | IRR: 0.1818
Running 33/100 | ID: 28026ee0-ae44-5a81-b89a-b10a92b18de2
Completed 33/100 | ID: 28026ee0-ae44-5a81-b89a-b10a92b18de2 | ROUGE-L: 0.2696 | Sim: 0.8116 | IRR: 0.0886
Running 34/100 | ID: 251cc796-4bfd-5b0b-aa60-188e059d99ca
Completed 34/100 | ID: 251cc796-4bfd-5b0b-aa60-188e059d99ca | ROUGE-L: 0.427 | Sim: 0.8457 | IRR: 0.7209
Running 35/100 | ID: fcb2ccfd-c106-5044-80af-281f9144b459
Completed 35/100 | ID: fcb2ccfd-c106-5044-80af-281f9144b459 | ROUGE-L: 0.335 | Sim: 0.7794 | IRR: 0.1364
Running 36/100 | ID: 2f9ca683-d99c-5ee1-9d3f-c5f2d36b12f7
Completed 36/100 | ID: 2f9ca683-d99c-5ee1-9d3f-c5f2d36b12f7 | ROUGE-L: 0.3273 | Sim: 0.836 | IRR: 0.1481
Running 37/100 | ID: 86d83e60-44a9-529f-a8f6-3f308989b533
Completed 37/100 | ID: 86d83e60-44a9-529f-a8f6-3f308989b533 | ROUGE-L: 0.3351 | Sim: 0.6847 | IRR: 0.2581
Running 38/100 | ID: 5c276aed-16cf-558a-9363-37ebe181c462
Completed 38/100 | ID: 5c276aed-16cf-558a-9363-37ebe181c462 | ROUGE-L: 0.3229 | Sim: 0.8088 | IRR: 0.3636
Running 39/100 | ID: 6d52ffe8-e7ac-5548-9aae-5b905a224208
Completed 39/100 | ID: 6d52ffe8-e7ac-5548-9aae-5b905a224208 | ROUGE-L: 0.3049 | Sim: 0.7304 | IRR: 0.2857
Running 40/100 | ID: 6abb5c07-f383-50e5-9a7c-d66ba6af608a
Completed 40/100 | ID: 6abb5c07-f383-50e5-9a7c-d66ba6af608a | ROUGE-L: 0.325 | Sim: 0.8944 | IRR: 0.2712
Running 41/100 | ID: ebf21b56-6c5c-5df5-bfeb-e44b454c8173
Completed 41/100 | ID: ebf21b56-6c5c-5df5-bfeb-e44b454c8173 | ROUGE-L: 0.3363 | Sim: 0.8504 | IRR: 0.5333
Running 42/100 | ID: 32bf53d9-5840-5c4d-b1e3-f96e5790adda
Completed 42/100 | ID: 32bf53d9-5840-5c4d-b1e3-f96e5790adda | ROUGE-L: 0.4103 | Sim: 0.8725 | IRR: 0.3684
Running 43/100 | ID: 973d5e7d-cfa8-574a-b139-d71c4d1542f0
Completed 43/100 | ID: 973d5e7d-cfa8-574a-b139-d71c4d1542f0 | ROUGE-L: 0.3471 | Sim: 0.8392 | IRR: 0.6087
Running 44/100 | ID: 54dd1e7e-0d56-5f7e-a226-87d0d5b0e5f5
Completed 44/100 | ID: 54dd1e7e-0d56-5f7e-a226-87d0d5b0e5f5 | ROUGE-L: 0.4458 | Sim: 0.6543 | IRR: 0.2333
Running 45/100 | ID: 14449bcb-7e57-5801-9942-5d1a5ab160d4
Completed 45/100 | ID: 14449bcb-7e57-5801-9942-5d1a5ab160d4 | ROUGE-L: 0.3735 | Sim: 0.8083 | IRR: 0.2222
Running 46/100 | ID: 8203a276-c40e-5d47-ac8b-950fd72eba9a
Completed 46/100 | ID: 8203a276-c40e-5d47-ac8b-950fd72eba9a | ROUGE-L: 0.4061 | Sim: 0.829 | IRR: 0.5517
Running 47/100 | ID: e62cd3be-14f4-59d7-ad22-f11779d840c3
Completed 47/100 | ID: e62cd3be-14f4-59d7-ad22-f11779d840c3 | ROUGE-L: 0.322 | Sim: 0.775 | IRR: 0.1463
Running 48/100 | ID: 9fdce2e7-0cdd-50aa-a96b-4925724eebc3
Completed 48/100 | ID: 9fdce2e7-0cdd-50aa-a96b-4925724eebc3 | ROUGE-L: 0.4431 | Sim: 0.7887 | IRR: 0.2024
Running 49/100 | ID: 03482579-ef9a-51f9-927b-c1d62cbbc269
Completed 49/100 | ID: 03482579-ef9a-51f9-927b-c1d62cbbc269 | ROUGE-L: 0.4818 | Sim: 0.9231 | IRR: 0.4889
Running 50/100 | ID: 76d9b04d-4364-50c9-a5cd-4d7d2936e436
Completed 50/100 | ID: 76d9b04d-4364-50c9-a5cd-4d7d2936e436 | ROUGE-L: 0.3524 | Sim: 0.8063 | IRR: 0.25
Running 51/100 | ID: 14f20381-ef38-53fd-8869-8ca7a1bc0f02
Completed 51/100 | ID: 14f20381-ef38-53fd-8869-8ca7a1bc0f02 | ROUGE-L: 0.33 | Sim: 0.773 | IRR: 0.2
Running 52/100 | ID: 0dc4dd91-4b95-5cdb-b269-c390fcd70012
Completed 52/100 | ID: 0dc4dd91-4b95-5cdb-b269-c390fcd70012 | ROUGE-L: 0.4258 | Sim: 0.8384 | IRR: 0.3571
Running 53/100 | ID: 546f2cc6-ce2d-55c4-9ee0-b4e792dabd25
Completed 53/100 | ID: 546f2cc6-ce2d-55c4-9ee0-b4e792dabd25 | ROUGE-L: 0.4058 | Sim: 0.898 | IRR: 0.5
Running 54/100 | ID: fa99b65c-6e5f-5874-8ecb-8cc661090440
Completed 54/100 | ID: fa99b65c-6e5f-5874-8ecb-8cc661090440 | ROUGE-L: 0.3089 | Sim: 0.7469 | IRR: 0.129
Running 55/100 | ID: fa940248-ac7c-5d92-a316-0951833269be
Completed 55/100 | ID: fa940248-ac7c-5d92-a316-0951833269be | ROUGE-L: 0.2769 | Sim: 0.8756 | IRR: 0.1667
Running 56/100 | ID: c9b2547a-5d87-5b26-9476-80116ff88eaa
Completed 56/100 | ID: c9b2547a-5d87-5b26-9476-80116ff88eaa | ROUGE-L: 0.3871 | Sim: 0.8598 | IRR: 0.4444
Running 57/100 | ID: e123908b-3127-59d3-a4fc-1f2d212066f1
Completed 57/100 | ID: e123908b-3127-59d3-a4fc-1f2d212066f1 | ROUGE-L: 0.358 | Sim: 0.8998 | IRR: 0.3214
Running 58/100 | ID: 8e0657fb-53d7-5574-8c07-02c4acf2275a
Completed 58/100 | ID: 8e0657fb-53d7-5574-8c07-02c4acf2275a | ROUGE-L: 0.4371 | Sim: 0.8115 | IRR: 0.1667
Running 59/100 | ID: a9a89f86-1cd6-5796-a12c-f27f5586768c
Completed 59/100 | ID: a9a89f86-1cd6-5796-a12c-f27f5586768c | ROUGE-L: 0.4949 | Sim: 0.9026 | IRR: 0.75
Running 60/100 | ID: 12ba88b7-36cf-5da1-aad1-3ec85ed7c5d7
Completed 60/100 | ID: 12ba88b7-36cf-5da1-aad1-3ec85ed7c5d7 | ROUGE-L: 0.322 | Sim: 0.8765 | IRR: 0.2308
Running 61/100 | ID: c25d70fa-3ed2-5172-bc1a-deb96b7e4665
Completed 61/100 | ID: c25d70fa-3ed2-5172-bc1a-deb96b7e4665 | ROUGE-L: 0.3744 | Sim: 0.8396 | IRR: 0.463
Running 62/100 | ID: 0c988373-a8d8-50fb-8a77-927249f479d1
Completed 62/100 | ID: 0c988373-a8d8-50fb-8a77-927249f479d1 | ROUGE-L: 0.4224 | Sim: 0.9004 | IRR: 0.1935
Running 63/100 | ID: 2f6021f0-6205-58d5-8dbb-5b30321d35e1
Completed 63/100 | ID: 2f6021f0-6205-58d5-8dbb-5b30321d35e1 | ROUGE-L: 0.2985 | Sim: 0.7986 | IRR: 0.1912
Running 64/100 | ID: 16a41c94-a45f-5a0f-8d61-749e0d5960bb
Completed 64/100 | ID: 16a41c94-a45f-5a0f-8d61-749e0d5960bb | ROUGE-L: 0.3815 | Sim: 0.83 | IRR: 0.5455
Running 65/100 | ID: 12832c95-9bb4-504e-8585-57777a1b0f5e
Completed 65/100 | ID: 12832c95-9bb4-504e-8585-57777a1b0f5e | ROUGE-L: 0.32 | Sim: 0.8091 | IRR: 0.4286
Running 66/100 | ID: 1e80dbc7-72e2-5ee9-81b7-38ead4f5e0ef
Completed 66/100 | ID: 1e80dbc7-72e2-5ee9-81b7-38ead4f5e0ef | ROUGE-L: 0.4044 | Sim: 0.8488 | IRR: 0.1212
Running 67/100 | ID: 46e03ffd-c215-57b4-a90d-01375f0a6d16
Completed 67/100 | ID: 46e03ffd-c215-57b4-a90d-01375f0a6d16 | ROUGE-L: 0.3616 | Sim: 0.752 | IRR: 0.1395
Running 68/100 | ID: 74145211-e88f-50b0-aa90-23b0efe6af62
Completed 68/100 | ID: 74145211-e88f-50b0-aa90-23b0efe6af62 | ROUGE-L: 0.2809 | Sim: 0.7256 | IRR: 0.0
Running 69/100 | ID: 4189a97b-fe35-57aa-852d-64a5b754685f
Completed 69/100 | ID: 4189a97b-fe35-57aa-852d-64a5b754685f | ROUGE-L: 0.2983 | Sim: 0.7742 | IRR: 0.15
Running 70/100 | ID: 55751942-3b14-5160-9c3b-8bf2914d4150
Completed 70/100 | ID: 55751942-3b14-5160-9c3b-8bf2914d4150 | ROUGE-L: 0.3962 | Sim: 0.8585 | IRR: 0.45
Running 71/100 | ID: 1fce7199-b9f4-508d-b4ad-62250dbc38aa
Completed 71/100 | ID: 1fce7199-b9f4-508d-b4ad-62250dbc38aa | ROUGE-L: 0.3308 | Sim: 0.7463 | IRR: 0.2051
Running 72/100 | ID: 0d80b70e-6388-5097-b2ed-58558eba3a57
Completed 72/100 | ID: 0d80b70e-6388-5097-b2ed-58558eba3a57 | ROUGE-L: 0.3135 | Sim: 0.7611 | IRR: 0.1818
Running 73/100 | ID: 39e2ee1d-7bb1-52b2-bbc3-81f80dbd2886
Completed 73/100 | ID: 39e2ee1d-7bb1-52b2-bbc3-81f80dbd2886 | ROUGE-L: 0.4384 | Sim: 0.8631 | IRR: 0.18
Running 74/100 | ID: 7b538c72-321d-5def-bde8-88422e6270e6
Completed 74/100 | ID: 7b538c72-321d-5def-bde8-88422e6270e6 | ROUGE-L: 0.3465 | Sim: 0.819 | IRR: 0.2162
Running 75/100 | ID: 94026418-6f5c-5499-998b-29afbcdcd912
Completed 75/100 | ID: 94026418-6f5c-5499-998b-29afbcdcd912 | ROUGE-L: 0.3541 | Sim: 0.8556 | IRR: 0.3205
Running 76/100 | ID: a7a876fc-383d-5ddb-a510-77125ff8cf95
Completed 76/100 | ID: a7a876fc-383d-5ddb-a510-77125ff8cf95 | ROUGE-L: 0.3744 | Sim: 0.8974 | IRR: 0.4054
Running 77/100 | ID: fb95c4ee-f1f7-588d-bacf-6ec14c920b0e
Completed 77/100 | ID: fb95c4ee-f1f7-588d-bacf-6ec14c920b0e | ROUGE-L: 0.3238 | Sim: 0.7425 | IRR: 0.2911
Running 78/100 | ID: 464e841d-3f55-588f-8356-586801c00850
Completed 78/100 | ID: 464e841d-3f55-588f-8356-586801c00850 | ROUGE-L: 0.3733 | Sim: 0.8123 | IRR: 0.1724
Running 79/100 | ID: 3ea7cd01-69ac-580c-a808-9457ef1b296a
Completed 79/100 | ID: 3ea7cd01-69ac-580c-a808-9457ef1b296a | ROUGE-L: 0.4225 | Sim: 0.875 | IRR: 0.2683
Running 80/100 | ID: d82e8142-5e21-5af4-8a41-cce0ff5b59c7
Completed 80/100 | ID: d82e8142-5e21-5af4-8a41-cce0ff5b59c7 | ROUGE-L: 0.4507 | Sim: 0.7516 | IRR: 0.5217
Running 81/100 | ID: b413238d-1c36-5dfc-8e25-7d37fd26bc56
Completed 81/100 | ID: b413238d-1c36-5dfc-8e25-7d37fd26bc56 | ROUGE-L: 0.4746 | Sim: 0.9024 | IRR: 0.3611
Running 82/100 | ID: 2c65603e-9e19-5561-b95e-2921dbfbe358
Completed 82/100 | ID: 2c65603e-9e19-5561-b95e-2921dbfbe358 | ROUGE-L: 0.2802 | Sim: 0.8021 | IRR: 0.4091
Running 83/100 | ID: dd46fd74-061d-5640-a21e-a8c555434f12
Completed 83/100 | ID: dd46fd74-061d-5640-a21e-a8c555434f12 | ROUGE-L: 0.264 | Sim: 0.8229 | IRR: 0.1852
Running 84/100 | ID: 8b0a00b0-5fde-5ab7-a29f-0cd9898e5bb8
Completed 84/100 | ID: 8b0a00b0-5fde-5ab7-a29f-0cd9898e5bb8 | ROUGE-L: 0.3038 | Sim: 0.8642 | IRR: 0.4375
Running 85/100 | ID: 46a14f36-622e-530f-91c4-ac1c88745f19
Completed 85/100 | ID: 46a14f36-622e-530f-91c4-ac1c88745f19 | ROUGE-L: 0.4671 | Sim: 0.7639 | IRR: 0.4
Running 86/100 | ID: 1e0b7068-e117-5c7f-b098-3cd1a179c361
Completed 86/100 | ID: 1e0b7068-e117-5c7f-b098-3cd1a179c361 | ROUGE-L: 0.3625 | Sim: 0.837 | IRR: 0.5
Running 87/100 | ID: 30a04a29-f476-590c-a034-c7981d25c09e
Completed 87/100 | ID: 30a04a29-f476-590c-a034-c7981d25c09e | ROUGE-L: 0.356 | Sim: 0.8905 | IRR: 0.2963
Running 88/100 | ID: 6dfd37d6-8de4-5b21-8e27-b7d041928281
Completed 88/100 | ID: 6dfd37d6-8de4-5b21-8e27-b7d041928281 | ROUGE-L: 0.4455 | Sim: 0.7636 | IRR: 0.3269
Running 89/100 | ID: f4a6d2c7-56cc-548d-8aab-e64303e680d4
Completed 89/100 | ID: f4a6d2c7-56cc-548d-8aab-e64303e680d4 | ROUGE-L: 0.1858 | Sim: 0.7702 | IRR: 0.2759
Running 90/100 | ID: 5f365830-a694-56a1-b9f5-e1149e7ac66b
Completed 90/100 | ID: 5f365830-a694-56a1-b9f5-e1149e7ac66b | ROUGE-L: 0.3885 | Sim: 0.7754 | IRR: 0.4419
Running 91/100 | ID: 23e1760f-74a9-5621-917f-f1f2e02775a8
Completed 91/100 | ID: 23e1760f-74a9-5621-917f-f1f2e02775a8 | ROUGE-L: 0.3046 | Sim: 0.8398 | IRR: 0.1667
Running 92/100 | ID: a94c0270-c53b-55eb-aff5-4f5d07a22dda
Completed 92/100 | ID: a94c0270-c53b-55eb-aff5-4f5d07a22dda | ROUGE-L: 0.4375 | Sim: 0.8497 | IRR: 0.3659
Running 93/100 | ID: dcc452a7-9e19-581a-93dc-efba899f5c35
Completed 93/100 | ID: dcc452a7-9e19-581a-93dc-efba899f5c35 | ROUGE-L: 0.3828 | Sim: 0.8606 | IRR: 0.3571
Running 94/100 | ID: 38e5127c-2f38-538d-9534-4fcfd9941167
Completed 94/100 | ID: 38e5127c-2f38-538d-9534-4fcfd9941167 | ROUGE-L: 0.3937 | Sim: 0.8703 | IRR: 0.5556
Running 95/100 | ID: b5f3672b-3347-5128-b933-ccfc2a337390
Completed 95/100 | ID: b5f3672b-3347-5128-b933-ccfc2a337390 | ROUGE-L: 0.3453 | Sim: 0.7787 | IRR: 0.3333
Running 96/100 | ID: bf207a7a-029b-58db-aad5-6211d632af5d
Completed 96/100 | ID: bf207a7a-029b-58db-aad5-6211d632af5d | ROUGE-L: 0.4424 | Sim: 0.8746 | IRR: 0.4194
Running 97/100 | ID: 8f856535-1fde-5138-a1bc-13df99cc0460
Completed 97/100 | ID: 8f856535-1fde-5138-a1bc-13df99cc0460 | ROUGE-L: 0.5 | Sim: 0.8103 | IRR: 0.0889
Running 98/100 | ID: f1bf1731-d1ce-5904-911c-8729eb56ca96
Completed 98/100 | ID: f1bf1731-d1ce-5904-911c-8729eb56ca96 | ROUGE-L: 0.2903 | Sim: 0.7117 | IRR: 0.1395
Running 99/100 | ID: 4f3ac694-0730-5739-afbb-7d09d2f5e97b
Completed 99/100 | ID: 4f3ac694-0730-5739-afbb-7d09d2f5e97b | ROUGE-L: 0.253 | Sim: 0.835 | IRR: 0.2105
Running 100/100 | ID: 01947a3a-b41d-5b59-a842-73beeb913ac7
Completed 100/100 | ID: 01947a3a-b41d-5b59-a842-73beeb913ac7 | ROUGE-L: 0.3429 | Sim: 0.7705 | IRR: 0.3684
Saved JSON to: /content/drive/MyDrive/Colab Notebooks/Masters/Masters_Thesis_Project/outputs/experiments/exp_s_05_few_shot_without_rag_llama-3.3-70b-versatile/exp_s_05_few_shot_without_rag_llama-3.3-70b-versatile.json
Saved CSV to : /content/drive/MyDrive/Colab Notebooks/Masters/Masters_Thesis_Project/outputs/experiments/exp_s_05_few_shot_without_rag_llama-3.3-70b-versatile/exp_s_05_few_shot_without_rag_llama-3.3-70b-versatile.csv

===== FINAL SUMMARY METRICS =====
ROUGE-L Mean: 0.3635
ROUGE-L Median: 0.3598
ROUGE-L Std: 0.0644
Semantic Similarity Mean: 0.8116
IRR Mean: 0.2981
Global Skill Overlap: 0.3299
Hallucination Rate Mean: 0.3355
Hallucination Prevalence: 1.0
Hallucination Density: 4.97
Compression Ratio Mean: 0.2546
Top-K Skill Coverage Mean: 0.31

Saved final metrics to: /content/drive/MyDrive/Colab Notebooks/Masters/Masters_Thesis_Project/outputs/experiments/exp_s_05_few_shot_without_rag_llama-3.3-70b-versatile/exp_s_05_few_shot_without_rag_llama-3.3-70b-versatile_final_metrics.csv
Saved final metrics JSON to: /content/drive/MyDrive/Colab Notebooks/Masters/Masters_Thesis_Project/outputs/experiments/exp_s_05_few_shot_without_rag_llama-3.3-70b-versatile/exp_s_05_few_shot_without_rag_llama-3.3-70b-versatile_final_metrics.json

,experiment_id,prompt_type,model_name,temperature,max_tokens,num_samples_completed,rougeL_f1_mean,rougeL_f1_median,rougeL_f1_std,rougeL_f1_min,...,compression_ratio_min,compression_ratio_max,top_k_skill_coverage_mean,top_k_skill_coverage_median,top_k_skill_coverage_std,top_k_skill_coverage_min,top_k_skill_coverage_max,global_skill_overlap,hallucination_prevalence,hallucination_density
0,exp_s_05_few_shot_without_rag_llama-3.3-70b-ve...,few_shot,llama-3.3-70b-versatile,0.0,700,100,0.3635,0.3598,0.0644,0.1858,...,0.1007,0.7671,0.31,0.4,0.2077,0.0,0.8,0.3299,1.0,4.97